"""
Generates simple but useful pytest tests for high-risk untested call sites.
In the real hackathon workflow IBM Bob would make these tests much smarter.
"""

from typing import List
from .models import CallSite, GeneratedTest


def generate_tests_for_sites(sites: List[CallSite], max_tests: int = 5) -> List[GeneratedTest]:
    """
    Create basic pytest test stubs for the most dangerous call sites.
    """
    tests = []
    seen = set()

    for i, site in enumerate(sites[:max_tests]):
        key = (site.file, site.function_name)
        if key in seen:
            continue
        seen.add(key)

        test_name = f"test_{site.function_name}_blast_radius_{i+1}"
        filename = f"test_blast_radius_{site.function_name}.py"

        content = f'''"""
Auto-generated by BlastRadius
Target: {site.file}:{site.lineno} → {site.function_name}()
Risk: {site.risk}
"""

import pytest

# TODO: Import the real module that contains the call
# from your_project.some_module import ...

def {test_name}():
    """
    This test was generated because the call to `{site.function_name}`
    at {site.file}:{site.lineno} appears to have no direct test coverage.
    
    Original line:
        {site.code_line}
    """
    # Arrange
    # TODO: set up the necessary objects / mocks

    # Act
    # result = ... call the code path that reaches {site.function_name}()

    # Assert
    # assert result == expected
    # For now we just make sure the test file is valid
    assert True, "Replace this with a real assertion"
'''

        tests.append(GeneratedTest(
            filename=filename,
            content=content,
            target_call_site=f"{site.file}:{site.lineno}"
        ))

    return tests