"""
Focused pytest generation for high-risk blast-radius call sites.
"""

import re
from typing import List

from .models import CallSite, GeneratedTest


def _module_for_file(file_path: str) -> str:
    parts = file_path.replace(
        "\\",
        "/",
    ).split("/")

    if parts and parts[-1].endswith(".py"):
        parts[-1] = parts[-1][:-3]

    if parts and parts[-1] == "__init__":
        parts.pop()

    return ".".join(
        part
        for part in parts
        if part and part != "."
    )


def _argument_for(name: str) -> str:
    name = name.lower()

    if any(
        word in name
        for word in (
            "items",
            "cart",
            "prices",
            "values",
            "numbers",
            "ids",
        )
    ):
        return "[1, 2, 3]"

    if any(
        word in name
        for word in (
            "discount",
            "percent",
            "rate",
            "ratio",
        )
    ):
        return "10.0"

    if any(
        word in name
        for word in (
            "price",
            "amount",
            "total",
            "value",
            "count",
            "limit",
            "index",
            "id",
        )
    ):
        return "10.0"

    if any(
        word in name
        for word in (
            "name",
            "text",
            "message",
            "email",
            "token",
            "query",
        )
    ):
        return '"example"'

    if any(
        word in name
        for word in (
            "data",
            "payload",
            "options",
            "config",
            "params",
        )
    ):
        return '{"example": 1}'

    if any(
        word in name
        for word in (
            "flag",
            "enabled",
            "active",
            "debug",
        )
    ):
        return "True"

    return "Mock()"


def _safe_name(value: str) -> str:
    cleaned = re.sub(
        r"[^a-zA-Z0-9_]+",
        "_",
        value,
    )

    return cleaned.strip("_") or "call"


def _caller_expression(
    site: CallSite,
) -> str:
    module = (
        site.module
        or _module_for_file(site.file)
    )

    args = ", ".join(
        _argument_for(name)
        for name in site.caller_params
    )

    if (
        site.caller_is_method
        and site.caller_qualname
    ):
        owner, method = (
            site.caller_qualname.rsplit(
                ".",
                1,
            )
        )

        instance = (
            f"{module}.{owner}."
            f"__new__({module}.{owner})"
        )

        return (
            f"{instance}.{method}({args})"
        )

    caller = site.caller_name

    if not caller:
        return (
            f"{module}."
            f"{site.function_name}"
            f"({args})"
        )

    return (
        f"{module}.{caller}"
        f"({args})"
    )


def generate_tests_for_sites(
    sites: List[CallSite],
    max_tests: int = 5,
) -> List[GeneratedTest]:
    """
    Execute the real caller and assert that the changed function/method
    is reached. This targets the dangerous edge rather than using `assert True`.
    """
    tests: List[GeneratedTest] = []
    seen = set()

    for index, site in enumerate(
        sites[:max_tests],
        start=1,
    ):
        key = (
            site.file,
            site.lineno,
            site.function_name,
            site.caller_qualname,
        )

        if key in seen:
            continue

        seen.add(key)

        caller_module = (
            site.module
            or _module_for_file(site.file)
        )

        target_module = (
            site.target_module
            or caller_module
        )

        target_qualname = (
            site.target_qualname
            or site.function_name
        )

        test_name = (
            f"test_"
            f"{_safe_name(site.function_name)}"
            f"_via_"
            f"{_safe_name(site.caller_name or 'caller')}"
            f"_{index}"
        )

        filename = (
            f"test_blast_radius_"
            f"{_safe_name(site.function_name)}"
            f"_{index}.py"
        )

        parts = target_qualname.split(".")

        target_attr = parts[-1]

        target_object = target_module

        if len(parts) > 1:
            target_object += "." + ".".join(
                parts[:-1]
            )

        call_expression = _caller_expression(
            site
        )

        content = f'''"""
Auto-generated by BlastRadius
Target: {site.file}:{site.lineno} -> {site.function_name}()
Risk: {site.risk} ({site.risk_score}/100)
"""

from unittest.mock import Mock

import {caller_module}
'''

        if target_module != caller_module:
            content += (
                f"import {target_module}\n"
            )

        content += f'''
def {test_name}(monkeypatch):
    """Exercise the production caller and verify the changed call is reached."""
    target_mock = Mock(return_value=1.0)

    monkeypatch.setattr(
        {target_object},
        "{target_attr}",
        target_mock,
    )

    {call_expression}

    target_mock.assert_called_once()
'''

        tests.append(
            GeneratedTest(
                filename=filename,
                content=content,
                target_call_site=(
                    f"{site.file}:{site.lineno}"
                ),
            )
        )

    return tests