"""Generate focused pytest checks for untested blast-radius call sites."""

import re
from typing import List, Optional

from .models import CallSite, GeneratedTest


def _module_for_file(file_path: str) -> str:
    parts = file_path.replace("\\", "/").split("/")
    if parts and parts[-1].endswith(".py"):
        parts[-1] = parts[-1][:-3]
    if parts and parts[-1] == "__init__":
        parts.pop()
    return ".".join(part for part in parts if part)


def _safe_name(value: str) -> str:
    value = re.sub(r"[^A-Za-z0-9_]+", "_", value)
    return value.strip("_") or "call"


def _argument_for(name: str) -> str:
    name = name.lower()
    if any(x in name for x in ("items", "cart", "prices", "values", "numbers", "ids")):
        return "[10.0, 20.0]"
    if any(x in name for x in ("discount", "percent", "rate", "ratio")):
        return "10.0"
    if any(x in name for x in ("price", "amount", "total", "value", "count", "limit", "index", "id")):
        return "10.0"
    if any(x in name for x in ("name", "text", "message", "email", "token", "query")):
        return '"example"'
    if any(x in name for x in ("data", "payload", "options", "config", "params")):
        return '{"example": 1}'
    if any(x in name for x in ("flag", "enabled", "active", "debug", "force")):
        return "True"
    return "Mock()"


def _return_value(site: CallSite) -> str:
    target = site.target_qualname or site.function_name
    # Most simple Python business functions can safely continue with a scalar.
    if any(x in target.lower() for x in ("format", "name", "text", "label")):
        return '"generated"'
    if any(x in target.lower() for x in ("list", "items")):
        return "[]"
    if any(x in target.lower() for x in ("dict", "data", "config")):
        return "{}"
    return "1.0"


def _caller_call(site: CallSite, module: str) -> Optional[str]:
    caller = site.caller_qualname
    args = ", ".join(_argument_for(name) for name in site.caller_params)

    if not caller or caller == "<module>":
        return None

    if site.caller_is_method and "." in caller:
        owner = caller.rsplit(".", 1)[0]
        return f"instance.{caller.rsplit('.', 1)[1]}({args})"

    return f"{module}.{site.caller_name}({args})"


def _patch_expression(site: CallSite, module: str) -> tuple[str, str]:
    patch_target = site.patch_target or module
    if "." in patch_target:
        owner, attr = patch_target.rsplit(".", 1)
        return owner, attr
    return patch_target, site.function_name


def generate_tests_for_sites(sites: List[CallSite], max_tests: int = 5) -> List[GeneratedTest]:
    tests: List[GeneratedTest] = []
    seen = set()

    for index, site in enumerate(sorted(sites, key=lambda x: x.risk_score, reverse=True), start=1):
        key = (site.file, site.lineno, site.function_name, site.caller_qualname)
        if key in seen:
            continue
        seen.add(key)

        module = site.module or _module_for_file(site.file)
        caller = site.caller_qualname or site.caller_name
        call = _caller_call(site, module)
        if call is None:
            continue

        test_name = f"test_{_safe_name(site.function_name)}_via_{_safe_name(site.caller_name or 'caller')}_{index}"
        filename = f"test_blast_radius_{_safe_name(site.function_name)}_{index}.py"
        owner_expr, target_attr = _patch_expression(site, module)

        imports = "from unittest.mock import Mock\n\n"
        imports += f"import {module}\n"

        body = f'''"""Generated by BlastRadius for {site.file}:{site.lineno}."""

{imports}

def {test_name}(monkeypatch):
    target_mock = Mock(return_value={_return_value(site)})
    monkeypatch.setattr({owner_expr}, "{target_attr}", target_mock)
'''

        if site.caller_is_method and caller and "." in caller:
            class_name = caller.rsplit(".", 1)[0]
            body += f"    instance = {module}.{class_name}.__new__({module}.{class_name})\n"

        body += f"    {call}\n    target_mock.assert_called_once()\n"
        body += f"    # BlastRadius target: {site.code_line}\n"

        tests.append(
            GeneratedTest(
                filename=filename,
                content=body,
                target_call_site=f"{site.file}:{site.lineno}",
            )
        )

        if len(tests) >= max_tests:
            break

    return tests
